mode: "mapElites" # interactive | mapElites | terrainBuilder | conventionalEA
printTimer: False
castleTilesFilepath: "resources/castleTiles/"

interactive:
    castleGenerationFilepath: "resources/castleGenerationInstructions/emptyKeep.txt" # emptyKeep.txt | test4.txt
    resolution: 4
    levelFilepath: "resources/terrainMaps/bridgedRiver2.txt" # bridgedRiver.txt | bridgedRiver2.txt | heightAndPath.txt

mapElites:
    levelFilepath: "resources/terrainMaps/bridgedRiver2.txt"
    archiveSavepath: "resources/archives/MapElites/"
    iterations: 2500
    population: 100
    resolution: 4
    useFitnessWithCost: False

terrainBuilder:
    levelFilepath: "resources/terrainMaps/bridgedRiver2.txt"
    resolution: 4
    maxHeightMultiplier: 1

conventionalEA:
    levelFilepath: "resources/terrainMaps/bridgedRiver2.txt"
    archiveSavepath: "resources/archives/ConventionalEA/"
    iterations: 1000
    population: 50
    resolution: 4
    useFitnessWithCost: True
