mode: "mapElites" # interactive | mapElites

interactive:
    castleGenerationFilepath: "resources/castleGenerationInstructions/test8.txt"
    resolution: 4
    levelFilepath: "resources/terrainMaps/perlinBy3.txt"
    castleTilesFilepath: "resources/castleTiles/"

mapElites:
    levelFilepath: "resources/terrainMaps/perlinBy4.txt"
    castleTilesFilepath: "resources/castleTiles/"
    archiveSavepath: "resources/archives/"
    iterations: 100
    population: 5
