mode: "mapElites" # interactive | mapElites

interactive:
    castleGenerationFilepath: "resources/castleGenerationInstructions/test4.txt"
    resolution: 4
    levelFilepath: "resources/terrainMaps/perlinBy3.txt"
    castleTilesFilepath: "resources/castleTiles/"

mapElites:
    levelFilepath: "resources/terrainMaps/perlinBy3.txt"
    castleTilesFilepath: "resources/castleTiles/"
    archiveSavepath: "resources/archives/"
    iterations: 200
    population: 20
    resolution: 4
