render: True
levelFilepath: "resources/terrainMaps/perlinBy3.txt"
castleGenerationFilepath: "resources/castleGenerationInstructions/test3.txt"
catleTilesFilepath: "resources/castleTiles/"
resolution: 8
