mode: "interactive" # interactive | mapElites | terrainBuilder
printTimer: True
castleTilesFilepath: "resources/castleTiles/"

interactive:
    castleGenerationFilepath: "resources/castleGenerationInstructions/test4.txt"
    resolution: 4
    levelFilepath: "resources/terrainMaps/perlinBy4 - test.txt"

mapElites:
    levelFilepath: "resources/terrainMaps/perlinBy4 - test.txt"
    archiveSavepath: "resources/archives/"
    iterations: 1000
    population: 25
    resolution: 4

terrainBuilder:
    levelFilepath: "resources/terrainMaps/perlinBy4 - test.txt"
    resolution: 4
    maxHeightMultiplier: 5
