mode: "mapElites" # interactive | mapElites
printTimer: False

interactive:
    castleGenerationFilepath: "resources/castleGenerationInstructions/test4.txt"
    resolution: 4
    levelFilepath: "resources/terrainMaps/perlinBy3.txt"
    castleTilesFilepath: "resources/castleTiles/"

mapElites:
    levelFilepath: "resources/terrainMaps/perlinBy4.txt"
    castleTilesFilepath: "resources/castleTiles/"
    archiveSavepath: "resources/archives/"
    iterations: 2000
    population: 200
    resolution: 4