render: True
levelFilepath: "resources/terrainMaps/perlinBy3.txt"
castleGenerationFilepath: "resources/castleGenerationInstructions/test7.txt"
catleTilesFilepath: "resources/castleTiles/"
resolution: 4