mode: "mapElites" # interactive | mapElites | terrainBuilder | conventionalEA
printTimer: False
castleTilesFilepath: "resources/castleTiles/"

interactive:
    castleGenerationFilepath: "resources/castleGenerationInstructions/test4.txt"
    resolution: 4
    levelFilepath: "resources/terrainMaps/onAHill.txt"

mapElites:
    levelFilepath: "resources/terrainMaps/onAHill.txt"
    archiveSavepath: "resources/archives/"
    iterations: 100
    population: 20
    resolution: 4

terrainBuilder:
    levelFilepath: "resources/terrainMaps/perlinBy30.txt"
    resolution: 4
    maxHeightMultiplier: 5

conventionalEA:
    levelFilepath: "resources/terrainMaps/perlinBy4 - test.txt"
    archiveSavepath: "resources/archives/"
    iterations: 50
    population: 20
    resolution: 4