mode: "conventionalEA" # interactive | mapElites | terrainBuilder | conventionalEA
printTimer: False
castleTilesFilepath: "resources/castleTiles/"

interactive:
    castleGenerationFilepath: "resources/castleGenerationInstructions/test4.txt"
    resolution: 4
    levelFilepath: "resources/terrainMaps/bridgedRiver.txt"

mapElites:
    levelFilepath: "resources/terrainMaps/bridgedRiver.txt"
    archiveSavepath: "resources/archives/MapElites/"
    iterations: 10
    population: 5
    resolution: 4
    useFitnessWithCost: False

terrainBuilder:
    levelFilepath: "resources/terrainMaps/bridgedRiver.txt"
    resolution: 4
    maxHeightMultiplier: 1

conventionalEA:
    levelFilepath: "resources/terrainMaps/mountain.txt"
    archiveSavepath: "resources/archives/ConventionalEA/"
    iterations: 20
    population: 5
    resolution: 4
    useFitnessWithCost: False
