mode: "conventionalEA" # interactive | mapElites | terrainBuilder | conventionalEA
printTimer: False
castleTilesFilepath: "resources/castleTiles/"

interactive:
    castleGenerationFilepath: "resources/castleGenerationInstructions/test4.txt"
    resolution: 4
    levelFilepath: "resources/terrainMaps/bridgedRiver.txt"

mapElites:
    levelFilepath: "resources/terrainMaps/mountain.txt"
    archiveSavepath: "resources/archives/"
    iterations: 800
    population: 20
    resolution: 4

terrainBuilder:
    levelFilepath: "resources/terrainMaps/mountain.txt"
    resolution: 4
    maxHeightMultiplier: 1

conventionalEA:
    levelFilepath: "resources/terrainMaps/perlinBy4 - test.txt"
    archiveSavepath: "resources/archives/"
    iterations: 50
    population: 20
    resolution: 4
