mode: "mapElites" # interactive | mapElites | terrainBuilder
printTimer: False
castleTilesFilepath: "resources/castleTiles/"

interactive:
    castleGenerationFilepath: "resources/castleGenerationInstructions/test4.txt"
    resolution: 4
    levelFilepath: "resources/terrainMaps/perlinBy4 - test.txt"

mapElites:
    levelFilepath: "resources/terrainMaps/perlinBy4 - test.txt"
    archiveSavepath: "resources/archives/"
    iterations: 10
    population: 5
    resolution: 4

terrainBuilder:
    levelFilepath: "resources/terrainMaps/perlinBy4 - test.txt"
    resolution: 4
    maxHeightMultiplier: 5
